# Site settings
title: Dapeng Xiong @ SEU
#email: dapengxiong@seu.edu.cn
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://dapeng-xiong.github.io/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title/
#jobtitle: "Docent"
excerpt_separator: "<!--more-->"

# SEO stuff
google_author: "https://plus.google.com/u/0/110288225974212014913"
google_site_verification: "nfd8hkZSc3GmIivrLCudAdTq5m1kI0Ao7P1UyIt9z5Q"
bing_webmastertools_id: "E24D33E8D53D5730794478CB209F15E5"

plugins_dir:
  - jekyll-sitemap

exclude: ['*.Rmd']
